import { Dataset, Indicator, Publication, Theme } from "./types";

export const themes: Theme[] = [
  {
    id: "1",
    name: "Economy",
    slug: "economy",
    description: "Macroeconomic indicators, inflation, trade, and labour market data.",
  },
  {
    id: "2",
    name: "Population & Demography",
    slug: "population-demography",
    description: "Population size, age structure, households, fertility, and migration.",
  },
  {
    id: "3",
    name: "Health",
    slug: "health",
    description: "Health facilities, mortality, immunization, and service access.",
  },
  {
    id: "4",
    name: "Education",
    slug: "education",
    description: "Enrolment, literacy, completion, and school access indicators.",
  },
  {
    id: "5",
    name: "Environment & Climate",
    slug: "environment-climate",
    description: "Rainfall, flooding, land use, and climate-related indicators.",
  },
  {
    id: "6",
    name: "Agriculture & Food Security",
    slug: "agriculture-food-security",
    description: "Crop production, livestock, food prices, and food security statistics.",
  },
];

export const indicators: Indicator[] = [
  {
    id: "i1",
    name: "Inflation Rate",
    slug: "inflation-rate",
    shortDescription: "Annual percentage change in consumer prices.",
    theme: "Economy",
    unit: "%",
    latestValue: 15.2,
    latestPeriod: "Jan 2026",
    trend: "up",
    series: [
      { label: "2021", value: 7.1 },
      { label: "2022", value: 9.8 },
      { label: "2023", value: 11.4 },
      { label: "2024", value: 12.7 },
      { label: "2025", value: 14.6 },
      { label: "2026", value: 15.2 },
    ],
    definition: "Inflation rate measures the annual percentage change in the consumer price index.",
    source: "National Bureau of Statistics",
    frequency: "Monthly",
  },
  {
    id: "i2",
    name: "Population Total",
    slug: "population-total",
    shortDescription: "Estimated total population of South Sudan.",
    theme: "Population & Demography",
    unit: "millions",
    latestValue: 12.4,
    latestPeriod: "2025",
    trend: "up",
    series: [
      { label: "2020", value: 11.4 },
      { label: "2021", value: 11.6 },
      { label: "2022", value: 11.8 },
      { label: "2023", value: 12.0 },
      { label: "2024", value: 12.2 },
      { label: "2025", value: 12.4 },
    ],
    definition: "Total estimated population across South Sudan.",
    source: "Population Estimates Unit",
    frequency: "Annual",
  },
  {
    id: "i3",
    name: "School Enrolment Rate",
    slug: "school-enrolment-rate",
    shortDescription: "Share of school-age children enrolled in school.",
    theme: "Education",
    unit: "%",
    latestValue: 58.1,
    latestPeriod: "2025",
    trend: "flat",
    series: [
      { label: "2020", value: 51.2 },
      { label: "2021", value: 53.4 },
      { label: "2022", value: 55.8 },
      { label: "2023", value: 56.9 },
      { label: "2024", value: 57.6 },
      { label: "2025", value: 58.1 },
    ],
    definition: "Percentage of school-age children enrolled in primary and secondary education.",
    source: "Education Management Information System",
    frequency: "Annual",
  },
  {
    id: "i4",
    name: "Vaccination Coverage",
    slug: "vaccination-coverage",
    shortDescription: "Coverage rate for routine childhood immunization.",
    theme: "Health",
    unit: "%",
    latestValue: 64.3,
    latestPeriod: "2025",
    trend: "up",
    series: [
      { label: "2020", value: 49.8 },
      { label: "2021", value: 52.6 },
      { label: "2022", value: 56.2 },
      { label: "2023", value: 59.4 },
      { label: "2024", value: 61.7 },
      { label: "2025", value: 64.3 },
    ],
    definition: "Percentage of target children receiving routine vaccination services.",
    source: "Ministry of Health",
    frequency: "Annual",
  },
];

export const publications: Publication[] = [
  {
    id: "p1",
    title: "Statistical Abstract 2025",
    slug: "statistical-abstract-2025",
    summary: "A consolidated annual overview of key statistics across sectors.",
    date: "2026-01-20",
    type: "Annual Report",
  },
  {
    id: "p2",
    title: "Monthly Price Bulletin — January 2026",
    slug: "monthly-price-bulletin-january-2026",
    summary: "Recent movement in consumer prices and inflation indicators.",
    date: "2026-02-05",
    type: "Bulletin",
  },
  {
    id: "p3",
    title: "Education Snapshot 2025",
    slug: "education-snapshot-2025",
    summary: "Key education participation and completion statistics for 2025.",
    date: "2026-01-10",
    type: "Factsheet",
  },
];

export const datasets: Dataset[] = [
  {
    id: "d1",
    title: "Consumer Price Index Monthly Series",
    slug: "consumer-price-index-monthly-series",
    description: "Monthly consumer price series for national and selected urban areas.",
    theme: "Economy",
    format: "CSV, XLSX",
    updatedAt: "2026-02-05",
  },
  {
    id: "d2",
    title: "State Population Estimates 2020–2025",
    slug: "state-population-estimates-2020-2025",
    description: "Population estimates by state and year.",
    theme: "Population & Demography",
    format: "CSV, XLSX",
    updatedAt: "2026-01-25",
  },
  {
    id: "d3",
    title: "Education Access Dataset",
    slug: "education-access-dataset",
    description: "Annual school access and enrolment figures by state.",
    theme: "Education",
    format: "CSV, PDF",
    updatedAt: "2026-01-12",
  },
];